### PR TITLE
Named parameters, contextualized errors, edge case bug fixes

### PR DESCRIPTION
**Pull request by kazazes**
I've made some modifications to your OLS implementation and figured I'd pass them along. See my commit messages. Specifically, ebaddc4 gets rid of some crashes I was facing when dealing with null values and 0'd out rows, and in 61f370f I added the ability to use named parameters by passing an array of strings corresponding to parameter names.

### CODE REVIEW

**Comment by akmiller01** [comment]
Never had someone contribute to my code! Thanks for taking a look.

**Comment by akmiller01** [comment]
Just out of curiosity, @kazazes, why did you chose to drop the robust standard errors? Simplification?

**Comment by kazazes** [comment]
@akmiller01, yeah, it was personal preference. I only intended to PR up to commit 61f370f, but never separated it to it's own branch. Great chunk of code, thank you.

**Comment by kazazes** [comment]
Some of my additions are pretty non-standard, including 7f43bd4 (Adjusted R2) and e9d8fa8 (Fstat and Fvalue).

**Pull request merged**
